# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)


### 2. Create a random tensor with shape `(7, 7)`.


In [8]:
# Import torch
import torch
# Create random tensor
ten_rand = torch.rand(7,7)
print(ten_rand)


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/aliyuyusuf/.pyenv/versions/3.12.0/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/aliyuyusuf/.pyenv/versions/3.12.0/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/aliyuyusuf/.pyenv/versions/3.12.0/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 739,

tensor([[0.6553, 0.1061, 0.4962, 0.2341, 0.6843, 0.8914, 0.3320],
        [0.3271, 0.8642, 0.7726, 0.1516, 0.6222, 0.0533, 0.1760],
        [0.6791, 0.3775, 0.4804, 0.6588, 0.9705, 0.1297, 0.4849],
        [0.2486, 0.9689, 0.5630, 0.8373, 0.3339, 0.0668, 0.4963],
        [0.1280, 0.2939, 0.6396, 0.6308, 0.5823, 0.7725, 0.3854],
        [0.1541, 0.1572, 0.1159, 0.4703, 0.4235, 0.1571, 0.4154],
        [0.6794, 0.6559, 0.0740, 0.5305, 0.9595, 0.8376, 0.8373]])


In [7]:
pip install torch

  Obtaining dependency information for torch from https://files.pythonhosted.org/packages/79/78/29dcab24a344ffd9ee9549ec0ab2c7885c13df61cde4c65836ee275efaeb/torch-2.2.2-cp312-none-macosx_10_9_x86_64.whl.metadata
  Obtaining dependency information for sympy from https://files.pythonhosted.org/packages/99/ff/c87e0622b1dadea79d2fb0b25ade9ed98954c9033722eb707053d310d4f3/sympy-1.13.3-py3-none-any.whl.metadata
  Obtaining dependency information for networkx from https://files.pythonhosted.org/packages/b9/54/dd730b32ea14ea797530a4479b2ed46a6fb250f682a9cfb997e968bf0261/networkx-3.4.2-py3-none-any.whl.metadata
  Obtaining dependency information for jinja2 from https://files.pythonhosted.org/packages/bd/0f/2ba5fbcd631e3e88689309dbe978c5769e883e4b84ebfe7da30b43275c5a/jinja2-3.1.5-py3-none-any.whl.metadata
  Obtaining dependency information for MarkupSafe>=2.0 from https://files.pythonhosted.org/packages/22/09/d1f21434c97fc42f09d290cbb6350d44eb12f09cc62c9476effdb33a18aa/MarkupSafe-3.0.2-cp312-cp31

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [10]:
# Create another random tensor
tensor1 = torch.rand(7, 7)
tensor2 = torch.rand(1, 7)
# Perform matrix multiplication, Note: tensor1 @ tensor2 is the most be inthesame diamention to perform matrix multiplication
# Therefore, tensor2 has to be transposed.
tensor3 = tensor1 @ tensor2.T
print(tensor3)

tensor([[2.6988],
        [1.6278],
        [3.0280],
        [2.1163],
        [1.9967],
        [1.8937],
        [2.0196]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [12]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_1 = torch.rand(7, 7)
tensor_2 = torch.rand(1, 7)
tensor_3 = tensor_2.T

# Matrix multiply tensors
result = torch.matmul(tensor_1, tensor_3)
print(result)
print(result.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])
torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [13]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [14]:
# Set random seed
torch.cuda.manual_seed(1234)

tensor_1 = torch.rand(2, 3)
tensor_2 = torch.rand(2, 3)

# Check for access to GPU
if torch.cuda.is_available():
    print('CUDA GPU is available')
else:
   print("Cuda GPU is not available")
# Create two random tensors on GPU
tensor_1 = tensor_1.cuda()
tensor_2 = tensor_2.cuda()
tensor_3 = tensor_1 + tensor_2
print(tensor_3)

Cuda GPU is not available


AssertionError: Torch not compiled with CUDA enabled

### Please not that the error is pop up becouse i use to code the on local machine.


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [15]:
# Perform matmul on tensor_A and tensor_B
tensor_A = torch.rand(2, 3)
tensor_B = torch.rand(3, 4)

tensor_C = torch.matmul(tensor_A, tensor_B)
print(tensor_C)


tensor([[1.3937, 0.9461, 0.5871, 1.0260],
        [1.4812, 0.4296, 0.7563, 1.0585]])


### 8. Find the maximum and minimum values of the output of 7.

In [16]:
tensor_C
# Find max
tensor_C.max()
# Find min
tensor_C.min()
print(tensor_C.max(), tensor_C.min())

tensor(1.4812) tensor(0.4296)


### 9. Find the maximum and minimum index values of the output of 7.

In [17]:
tensor_C
# Find arg max
tensor_C.argmax()

# Find arg min
tensor_C.argmin()

print(tensor_C.argmax(), tensor_C.argmin())

tensor(4) tensor(5)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [20]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(1, 1, 1, 10)
# Remove single dimensions
remove_tensor = torch.squeeze(tensor)

# Print out tensors and their shapes
print(remove_tensor)
print(remove_tensor.shape)

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
